### ISSUE TITLE
syntax error

### ISSUE THREAD

**Issue by dalek2point3** [philshem/open-spelling-bee#13]
python3 play_puzzle.py RDGHNOU
Traceback (most recent call last):
  File "play_puzzle.py", line 6, in <module>
    import utils
  File "open-spelling-bee/utils.py", line 6, in <module>
    import generate_puzzles
  File "open-spelling-bee/generate_puzzles.py", line 182
    print (f'unique {params.TOTAL_LETTER_COUNT}-letter pool: '+str(len(pool)))
                                                             ^
SyntaxError: invalid syntax

**Comment by philshem** [comment]
It could be an invalid printing method (f-string) which was introduced in Python 3.6 ([PEP 498](https://www.python.org/dev/peps/pep-0498/)).

Which version of python3 are you using? You can find it with this command.

    > python --version
    Python 3.7.3
